version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: point-blank:latest
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/point_blank
    volumes:
      - .:/rails
    command: bundle exec rails s -b 0.0.0.0

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: point_blank
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
