# Exported from Render on 2024-07-09T08:24:43Z

databases:
  - name: postgres
    plan: free


services:
  - type: web
    name: point-blank
    runtime: docker
    repo: https://github.com/nijeesh4all/point-blank
    plan: free
    
    envVars:
    - key: RAILS_MASTER_KEY
      sync: false
    - key: WEB_CONCURRENCY
      sync: false
    - key: DATABASE_URL
      fromDatabase:
        name: postgres
        property: connectionString
    - key: REDIS_URL
      fromService:
        type: redis
        name: sidekiq-redis
        property: connectionString
    
    region: oregon
    dockerContext: .
    dockerfilePath: ./Dockerfile
    autoDeploy: false

  - type: redis
    name: sidekiq-redis
    region: ohio
    maxmemoryPolicy: noeviction
    plan: free
    ipAllowList:
      - 0.0.0.0/0

  - type: worker
    plan: free
    region: oregon

    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: sidekiq-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString

    name: sidekiq-worker
    dockerContext: .
    dockerfilePath: ./Dockerfile
    runtime: docker


version: "1"