name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: List files
      run: ls -la


    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'

    - name: Install dependencies
      run: bundle install
      
    - name: versions
      run: |
        echo $(ruby -v)
        echo $(bundler -v)
        echo "Ruby Gems version $(gem --version)"

    - name: Set up database
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rails db:create
        bundle exec rails db:schema:load

    - name: Run RSpec tests
      run: bundle exec rspec

    - name: Run Brakeman
      run: bundle exec brakeman --format html --output brakeman.html

    - name: Upload Brakeman report
      uses: actions/upload-artifact@v2
      with:
        name: brakeman-report
        path: brakeman.html

    - name: Run Bundle Audit
      run: gem install bundler-audit && bundle exec bundle-audit check --update

    - name: Run Rubocop
      run: bundle exec rubocop
    
    - name: Run Rspecs
      run: bundle exec rspec
