name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'

    - name: Install dependencies
      run: bundle install

  linting:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'

    - name: Install dependencies
      run: bundle install

    - name: Run Rubocop
      run: bundle exec rubocop --disable-pending-cops

  sca:
    runs-on: ubuntu-latest
    needs: setup

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'

    - name: Install dependencies
      run: bundle install

    - name: Run Brakeman
      run: bundle exec brakeman --format html --output brakeman.html

    - name: Upload Brakeman report
      uses: actions/upload-artifact@v2
      with:
        name: brakeman-report
        path: brakeman.html

  tests:
    runs-on: ubuntu-latest
    needs: setup

    env:
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: myapp_test
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1.3'

    - name: Install dependencies
      run: bundle install

    - name: Set up database
      run: |
        cp config/database.yml.ci config/database.yml
        bundle exec rails db:create
        bundle exec rails db:schema:load

    - name: Run RSpec tests
      run: bundle exec rspec
